# Generated by Django 4.1.1 on 2023-02-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0002_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="description",
            field=models.CharField(default="", max_length=600),
            preserve_default=False,
        ),
    ]
