# Generated by Django 4.1.1 on 2023-02-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0003_training_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="time",
            field=models.CharField(max_length=12),
        ),
    ]
