# Generated by Django 4.1.1 on 2023-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0004_alter_training_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="calendar_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
