# Generated by Django 4.1.1 on 2023-02-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0005_training_calendar_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=600)),
                ("time", models.CharField(max_length=12)),
                ("day", models.CharField(max_length=10)),
                ("calendar_index", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
