# Generated by Django 4.1.1 on 2023-02-28 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0006_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="cardio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=10)),
                ("distance", models.IntegerField(blank=True, null=True)),
                ("time", models.CharField(max_length=10)),
                ("speed", models.CharField(max_length=10)),
                ("discipline", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
