# Generated by Django 4.1.1 on 2023-02-28 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0007_cardio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardio",
            name="day",
        ),
        migrations.AddField(
            model_name="cardio",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cardio",
            name="time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
