# Generated by Django 4.1.1 on 2023-02-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0008_remove_cardio_day_cardio_date_alter_cardio_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardio",
            name="distance",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
