# Generated by Django 4.1.1 on 2023-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0010_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="notes",
            field=models.CharField(max_length=200),
        ),
    ]
