# Generated by Django 4.1.1 on 2023-03-06 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0011_alter_measurement_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
