# Generated by Django 4.1.1 on 2023-03-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fit", "0012_measurement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="notes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
